#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Sat Dec 14 11:48:48 +03 2024
# SW Build 2552052 on Fri May 24 14:47:09 MDT 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xsim UART_Top_sim_behav -key {Behavioral:sim_1:Functional:UART_Top_sim} -tclbatch UART_Top_sim.tcl -view /home/it/Downloads/ChipXprt_DSD_pro-Raid/DSD_pro/UART_TOP/TOP/UART_Top_sim_behav.wcfg -log simulate.log"
xsim UART_Top_sim_behav -key {Behavioral:sim_1:Functional:UART_Top_sim} -tclbatch UART_Top_sim.tcl -view /home/it/Downloads/ChipXprt_DSD_pro-Raid/DSD_pro/UART_TOP/TOP/UART_Top_sim_behav.wcfg -log simulate.log

