#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.1 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Wed Dec 11 16:29:11 +03 2024
# SW Build 2552052 on Fri May 24 14:47:09 MDT 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto 7c32a803101144f58f8fa02fe5ceb2f8 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot Rx_DP_sim_behav xil_defaultlib.Rx_DP_sim xil_defaultlib.glbl -log elaborate.log"
xelab -wto 7c32a803101144f58f8fa02fe5ceb2f8 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot Rx_DP_sim_behav xil_defaultlib.Rx_DP_sim xil_defaultlib.glbl -log elaborate.log

